"""Initial migration script"""
"""Initial migration

Revision ID: 0001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('owner_label', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoints_hostname'), 'endpoints', ['hostname'], unique=False)
    op.create_index(op.f('ix_endpoints_id'), 'endpoints', ['id'], unique=False)
    op.create_index('idx_endpoint_hostname_platform', 'endpoints', ['hostname', 'platform'], unique=False)
    
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_endpoint_id'), 'telemetry', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_telemetry_id'), 'telemetry', ['id'], unique=False)
    op.create_index('idx_telemetry_endpoint_collected', 'telemetry', ['endpoint_id', 'collected_at'], unique=False)
    
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_endpoint_id'), 'findings', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_findings_id'), 'findings', ['id'], unique=False)
    op.create_index(op.f('ix_findings_rule_id'), 'findings', ['rule_id'], unique=False)
    op.create_index('idx_finding_endpoint_rule', 'findings', ['endpoint_id', 'rule_id'], unique=False)
    op.create_index('idx_finding_severity', 'findings', ['severity'], unique=False)
    
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_endpoint_id'), 'scores', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_scores_id'), 'scores', ['id'], unique=False)
    op.create_index('idx_score_endpoint_computed', 'scores', ['endpoint_id', 'computed_at'], unique=False)
    
    op.create_table('remediations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('audit_log', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_remediations_endpoint_id'), 'remediations', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_remediations_id'), 'remediations', ['id'], unique=False)
    op.create_index(op.f('ix_remediations_request_id'), 'remediations', ['request_id'], unique=False)
    op.create_index('idx_remediation_endpoint_status', 'remediations', ['endpoint_id', 'status'], unique=False)
    op.create_index('idx_remediation_request_id', 'remediations', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_remediation_request_id', table_name='remediations')
    op.drop_index('idx_remediation_endpoint_status', table_name='remediations')
    op.drop_index(op.f('ix_remediations_request_id'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_id'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_endpoint_id'), table_name='remediations')
    op.drop_table('remediations')
    
    op.drop_index('idx_score_endpoint_computed', table_name='scores')
    op.drop_index(op.f('ix_scores_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_endpoint_id'), table_name='scores')
    op.drop_table('scores')
    
    op.drop_index('idx_finding_severity', table_name='findings')
    op.drop_index('idx_finding_endpoint_rule', table_name='findings')
    op.drop_index(op.f('ix_findings_rule_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_endpoint_id'), table_name='findings')
    op.drop_table('findings')
    
    op.drop_index('idx_telemetry_endpoint_collected', table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_endpoint_id'), table_name='telemetry')
    op.drop_table('telemetry')
    
    op.drop_index('idx_endpoint_hostname_platform', table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_id'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_hostname'), table_name='endpoints')
    op.drop_table('endpoints')
    # ### end Alembic commands ###
